demo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newYear/', include("newYear.urls")),
    path('tasks/', include("tasks.urls")),
]

hello/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("hamza", views.hamza, name="hamza"),
    path("ilham", views.ilham, name="ilham"),
    path("radia", views.radia, name="radia"),
    # now instead of defining a route for each name we want to greet we will define a dynamic route that will take the "name" as a parameter which is a very useful feature 
    path("<str:name>", views.greet, name="greet"),
]

newYear/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

tasks/urls.py
from django.urls import path

from . import views

# the app name is because we have that one route named index
app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add/", views.add, name="add"),
]

tasks/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "hello/index.html") 

def hamza(request):
    return HttpResponse("Hello, Hamza!")

def ilham(request):
    return HttpResponse("Hello, Ilham!")

def radia(request):
    return HttpResponse("Hello, Radia!")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    }) 
    

newYear/views.py
import datetime

from django.shortcuts import render

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newYear/index.html", {
        "isItReallyNewYear": now.month == 1 and now.day == 1
    })

tasks/views.py
from django import forms

from django.shortcuts import render

tasks = [ "shop", "work", "pray", "eat", "sleep" ]	

class NewTaskForm(forms.Form):
    task = forms.CharField(label="Add New Task")
    priority = forms.IntegerField(label="Priority", min_value=1, max_value=8)

# Create your views here.
def index(request):
    # now we will pass those tasks in an array as an argument and catch them in the html file
    return render(request, "tasks/index.html", {
        "tasks": tasks
    })

def add(request):
    if request.method == "POST":
        # validating the data in the server side
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            tasks.append(task)
        else:
            return render(request, "tasks/add.html", {
                "form": form
            })

    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello {{ name }}!</h1>
</body>
</html>

hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    wa tcha raah hadchi bda kayziyaan
</body>
</html>

newYear/templates/newYear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'newYear/styles.css' %}">
    <title>Document</title>
</head>
<body>
    <h1>{% if isItReallyNewYear %}YES{% else %}NO{% endif %}</h1>
</body>
</html>

tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Add Task</h1>

    <form action="{% url 'tasks:add' %}" method="post">
        <!-- this token is neccessary for cross site request forgery and is a security layer needed during form submitting -->
        {% csrf_token %}
        <!-- <input type="text" name="task" placeholder="{{ task }}"> -->
        {{ form }}
        <button type="submit">Add task</button>
        <a href="{% url 'tasks:index' %}">View Tasks</a>
    </form>
{% endblock %}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Tasks</h1>
    <ul>
        {% for task in tasks %}
        <li>{{ task }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'add' %}">Add task to the list</a>
{% endblock %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>This is the header</header>
    {% block body %}
    {% endblock %}
</body>
</html>